import { useEffect, useRef, useState } from 'react'
import styles from './App.module.css'
type Lang='en'|'es'|'fr'
const C={
en:{nav:['Story','Menu','We ♥ Sushi','Gallery','Visit'],find:'Find us',k:'Creative cuisine · Costa Rica',h:'Where the world meets',ha:'the fire.',lead:'A borderless dining experience by Chef Steven Varela Jiménez—bold sushi, tropical ingredients and plates made with soul.',explore:'Explore the menu',story:'Our story',tick:['International cuisine','We love sushi','Special events','Catering service','Craft beer'],ak:'The chef behind the vision',ah:'Technique, instinct, and a world of flavor.',ap:'Chef Steven Varela Jiménez transforms Costa Rica’s abundance into expressive cuisine. His kitchen moves freely between Japanese precision, Latin warmth and international technique—always guided by fresh ingredients and generous hospitality.',quote:'Every plate should feel familiar for one second—and completely new the next.',mk:'Eight pages of possibilities',mh:'A menu without borders.',mp:'Sushi, seafood, premium cuts, vibrant salads and comforting classics—created for every kind of craving.',open:'Open full menu',down:'Download PDF',sk:'鮨 · Japanese craft, tropical soul',sh1:'We ',sh2:' Sushi',sp:'Hand-rolled. Fearlessly creative. Made to order with selected seafood, balanced rice and unexpected Costa Rican character.',gk:'From our kitchen',gh:'Food worth gathering around.',gp:'A visual taste of the dishes, colors and details that define Fusión.',vk:'Come as you are',vh:'Your table is waiting.',vp:'Share the exact Google Maps link, phone number and opening hours with us and this panel is ready to go live.',maps:'Open Google Maps',contact:'Contact restaurant',foot:'Creative cuisine · Sushi · Good times',by:'Website created by',full:'Full Menu',back:'Back to restaurant',mi:'Browse every page or download the complete menu for offline access.'},
es:{nav:['Historia','Menú','Amamos el sushi','Galería','Visítanos'],find:'Cómo llegar',k:'Cocina creativa · Costa Rica',h:'Donde el mundo se encuentra con',ha:'el fuego.',lead:'Una experiencia sin fronteras del chef Steven Varela Jiménez: sushi audaz, ingredientes tropicales y platos hechos con alma.',explore:'Explorar el menú',story:'Nuestra historia',tick:['Comida internacional','Amamos el sushi','Eventos especiales','Servicio de catering','Cerveza artesanal'],ak:'El chef detrás de la visión',ah:'Técnica, instinto y un mundo de sabor.',ap:'El chef Steven Varela Jiménez transforma la abundancia de Costa Rica en una cocina expresiva. Su propuesta une precisión japonesa, calidez latina y técnica internacional, siempre con ingredientes frescos y hospitalidad genuina.',quote:'Cada plato debe sentirse familiar por un segundo y completamente nuevo al siguiente.',mk:'Ocho páginas de posibilidades',mh:'Un menú sin fronteras.',mp:'Sushi, mariscos, cortes premium, ensaladas vibrantes y clásicos reconfortantes para todos los gustos.',open:'Abrir menú completo',down:'Descargar PDF',sk:'鮨 · Arte japonés, alma tropical',sh1:'Amamos el ',sh2:' Sushi',sp:'Enrollado a mano, creativo y preparado al momento con mariscos seleccionados, arroz equilibrado y carácter costarricense.',gk:'Desde nuestra cocina',gh:'Comida para compartir.',gp:'Una mirada a los platos, colores y detalles que definen a Fusión.',vk:'Ven como eres',vh:'Tu mesa te espera.',vp:'Compártenos el enlace exacto de Google Maps, teléfono y horario para dejar este panel listo para publicar.',maps:'Abrir Google Maps',contact:'Contactar restaurante',foot:'Cocina creativa · Sushi · Buenos momentos',by:'Página creada por',full:'Menú completo',back:'Volver al restaurante',mi:'Explora cada página o descarga el menú completo.'},
fr:{nav:['Histoire','Menu','Nous ♥ Sushi','Galerie','Visite'],find:'Nous trouver',k:'Cuisine créative · Costa Rica',h:'Là où le monde rencontre',ha:'le feu.',lead:'Une expérience sans frontières du chef Steven Varela Jiménez : sushi audacieux, ingrédients tropicaux et assiettes pleines d’âme.',explore:'Explorer le menu',story:'Notre histoire',tick:['Cuisine internationale','Nous aimons le sushi','Événements spéciaux','Service traiteur','Bière artisanale'],ak:'Le chef derrière la vision',ah:'Technique, instinct et un monde de saveurs.',ap:'Le chef Steven Varela Jiménez transforme l’abondance du Costa Rica en cuisine expressive, entre précision japonaise, chaleur latine et technique internationale.',quote:'Chaque assiette doit sembler familière une seconde, puis entièrement nouvelle.',mk:'Huit pages de possibilités',mh:'Un menu sans frontières.',mp:'Sushi, fruits de mer, viandes premium, salades vibrantes et grands classiques.',open:'Ouvrir le menu',down:'Télécharger le PDF',sk:'鮨 · Art japonais, âme tropicale',sh1:'Nous ',sh2:' Sushi',sp:'Roulé à la main, créatif et préparé sur commande avec des produits sélectionnés et un caractère costaricien.',gk:'Depuis notre cuisine',gh:'Une cuisine à partager.',gp:'Les plats, couleurs et détails qui définissent Fusión.',vk:'Venez comme vous êtes',vh:'Votre table vous attend.',vp:'Partagez le lien Google Maps exact, le téléphone et les horaires pour finaliser ce panneau.',maps:'Ouvrir Google Maps',contact:'Contacter le restaurant',foot:'Cuisine créative · Sushi · Bons moments',by:'Site créé par',full:'Menu complet',back:'Retour au restaurant',mi:'Parcourez chaque page ou téléchargez le menu complet.'}}
const sushi=[1,2,3,4,5,6,7,8,9,10].map(n=>`/media/sushi/sushi${String(n).padStart(2,'0')}.jpg`)
const food=[1,8,11,3,13,9,7,10,6,4,5].map(n=>`/media/food/comida${n}.jpg`)
type MenuCategory='international'|'specialties'|'japanese'
const menuCategories:{id:MenuCategory,label:Record<Lang,string>,kana:string}[]=[
 {id:'international',label:{en:'International',es:'Internacional',fr:'International'},kana:'世界の味'},
 {id:'specialties',label:{en:'House Specialties',es:'Especialidades',fr:'Spécialités'},kana:'おすすめ'},
 {id:'japanese',label:{en:'Japanese & Sushi',es:'Japonés y Sushi',fr:'Japonais & Sushi'},kana:'和食・寿司'}
]
const menus:{src:string,category:MenuCategory,title:Record<Lang,string>}[]=[
 {src:'/media/menu/01-international-starters.jpg',category:'international',title:{en:'International Starters',es:'Entradas Internacionales',fr:'Entrées Internationales'}},
 {src:'/media/menu/02-ceviches-pasta-rice.jpg',category:'international',title:{en:'Ceviches, Pasta & Rice',es:'Ceviches, Pastas y Arroces',fr:'Ceviches, Pâtes et Riz'}},
 {src:'/media/menu/03-seafood-signatures.jpg',category:'international',title:{en:'Seafood & Signature Mains',es:'Mariscos y Platos de Autor',fr:'Fruits de Mer et Plats Signature'}},
 {src:'/media/menu/04-premium-desserts.jpg',category:'international',title:{en:'Premium Cuts & Desserts',es:'Cortes Premium y Postres',fr:'Coupes Premium et Desserts'}},
 {src:'/media/menu/05-bocas.jpg',category:'specialties',title:{en:'Bocas & Casual Favorites',es:'Bocas y Favoritos',fr:'Bocas et Favoris'}},
 {src:'/media/menu/06-japanese-starters.jpg',category:'japanese',title:{en:'Japanese Starters',es:'Entradas Japonesas',fr:'Entrées Japonaises'}},
 {src:'/media/menu/07-sushi-rolls.jpg',category:'japanese',title:{en:'Signature Sushi Rolls',es:'Rollos de Sushi de Autor',fr:'Rouleaux de Sushi Signature'}},
 {src:'/media/menu/08-japanese-mains.jpg',category:'japanese',title:{en:'Japanese Mains',es:'Platos Fuertes Japoneses',fr:'Plats Japonais'}}
]
const mapUrl='https://www.google.com/maps/place/Restaurante+y+Bar+Fusi%C3%B3n/@9.0806844,-83.6667255,15.25z/data=!4m9!1m2!2m1!1sfusion!3m5!1s0x8fa3fe8e55a99541:0xc77a745b73b5d020!8m2!3d9.0808814!4d-83.6634834!16s%2Fg%2F11c2pq9rt8?entry=ttu'
const visitDetails={
  en:{text:'Plan your visit to Restaurante y Bar Fusión. Explore the interactive map or open Google Maps for turn-by-turn directions.',button:'Get directions'},
  es:{text:'Planea tu visita a Restaurante y Bar Fusión. Explora el mapa interactivo o abre Google Maps para recibir indicaciones paso a paso.',button:'Cómo llegar'},
  fr:{text:'Planifiez votre visite au Restaurante y Bar Fusión. Consultez la carte interactive ou ouvrez Google Maps pour obtenir votre itinéraire.',button:'Obtenir l’itinéraire'},
}
const galleryDetails={
  en:{more:'View more dishes',title:'The Fusión Gallery',close:'Close gallery',location:'Restaurante y Bar Fusión · Costa Rica',directions:'Directions'},
  es:{more:'Ver más platillos',title:'Galería Fusión',close:'Cerrar galería',location:'Restaurante y Bar Fusión · Costa Rica',directions:'Cómo llegar'},
  fr:{more:'Voir plus de plats',title:'Galerie Fusión',close:'Fermer la galerie',location:'Restaurante y Bar Fusión · Costa Rica',directions:'Itinéraire'},
}
const heroVideos=[
 {desktop:'/media/video/hero-fire.mp4',mobile:'/media/video/hero-fire-mobile.mp4',poster:'/media/video/hero-fire.jpg'},
 {desktop:'/media/video/hero-sushi.mp4',mobile:'/media/video/hero-sushi-mobile.mp4',poster:'/media/video/hero-sushi.jpg'},
 {desktop:'/media/video/hero-craft.mp4',mobile:'/media/video/hero-craft-mobile.mp4',poster:'/media/video/hero-craft.jpg'},
]
function Language({lang,set}:{lang:Lang,set:(v:Lang)=>void}){return <div className={styles.lang}>{(['en','es','fr'] as Lang[]).map(x=><button className={lang===x?styles.active:''} onClick={()=>set(x)} key={x}>{x.toUpperCase()}</button>)}</div>}
function MenuPage({lang,set}:{lang:Lang,set:(v:Lang)=>void}){
 const t=C[lang], [category,setCategory]=useState<'all'|MenuCategory>('all')
 const allLabel={en:'Explore all',es:'Ver todo',fr:'Tout voir'}[lang]
 const eyebrow={en:'A culinary journey',es:'Un viaje culinario',fr:'Un voyage culinaire'}[lang]
 const copy={en:'Creative cuisine rooted in Costa Rica, inspired by the world and elevated by Japanese technique.',es:'Cocina creativa con raíces en Costa Rica, inspirada en el mundo y elevada por la técnica japonesa.',fr:'Une cuisine créative enracinée au Costa Rica, inspirée du monde et sublimée par la technique japonaise.'}[lang]
 const shown=category==='all'?menus:menus.filter(menu=>menu.category===category)
 return <main className="menu-page-pro">
  <header className="menu-nav-pro"><a href="/">← {t.back}</a><span>FUSIÓN · SUSHI</span><Language lang={lang} set={set}/></header>
  <section className="menu-hero-pro">
   <div className="menu-hero-glow"/><div className="menu-kanji" aria-hidden="true">献立</div>
   <div className="menu-hero-copy" data-r><span>{eyebrow}</span><h1>{t.full}</h1><p>{copy}</p>
    <a className="menu-download-pro" href="/downloads/fusion-sushi-menu.pdf" download>{t.down}<b>↓</b></a>
   </div>
  </section>
  <nav className="menu-filter-pro" aria-label="Menu categories">
   <button className={category==='all'?'is-active':''} onClick={()=>setCategory('all')}><small>00</small>{allLabel}</button>
   {menuCategories.map((item,i)=><button key={item.id} className={category===item.id?'is-active':''} onClick={()=>setCategory(item.id)}><small>0{i+1}</small>{item.label[lang]}<em>{item.kana}</em></button>)}
  </nav>
  <section className="menu-catalog-pro" aria-live="polite">
   <div className="menu-catalog-heading" data-r><span>{shown.length.toString().padStart(2,'0')} / 08</span><h2>{category==='all'?allLabel:menuCategories.find(item=>item.id===category)?.label[lang]}</h2></div>
   <div className="menu-grid-pro">{shown.map((menu,i)=>{const cat=menuCategories.find(item=>item.id===menu.category)!;return <figure key={menu.src} data-r>
    <div className="menu-image-pro"><img src={menu.src} alt={`${menu.title[lang]} — ${i+1}`}/><a href={menu.src} target="_blank" rel="noreferrer" aria-label={`${menu.title[lang]} — open full size`}>↗</a></div>
    <figcaption><span>{cat.label[lang]} · {cat.kana}</span><h3>{menu.title[lang]}</h3><b>{String(menus.indexOf(menu)+1).padStart(2,'0')}</b></figcaption>
   </figure>})}</div>
  </section>
 </main>
}
function App(){const[lang,setLang]=useState<Lang>('en'),[open,setOpen]=useState(false),[hero,setHero]=useState(0),[galleryOpen,setGalleryOpen]=useState(false);const heroRefs=useRef<(HTMLVideoElement|null)[]>([]),t=C[lang];useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle(styles.visible,e.isIntersecting)),{threshold:.08,rootMargin:'-5% 0px -8%'});document.querySelectorAll('[data-r]').forEach(e=>o.observe(e));let ticking=false;const move=()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{document.documentElement.style.setProperty('--page-scroll',`${window.scrollY}px`);document.querySelectorAll<HTMLElement>('[data-parallax]').forEach(el=>{const rect=el.getBoundingClientRect();el.style.setProperty('--parallax',`${(rect.top-window.innerHeight/2)*-.035}px`)});ticking=false})};window.addEventListener('scroll',move,{passive:true});move();return()=>{o.disconnect();window.removeEventListener('scroll',move)}},[]);useEffect(()=>{const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduce)return;const rotate=()=>{if(!document.hidden)setHero(current=>(current+1)%heroVideos.length)};const timer=window.setInterval(rotate,9000);return()=>window.clearInterval(timer)},[]);useEffect(()=>{heroRefs.current.forEach((video,index)=>{if(!video)return;if(index===hero&&!document.hidden)video.play().catch(()=>{});else video.pause()});const visibility=()=>{const active=heroRefs.current[hero];if(!active)return;if(document.hidden)active.pause();else active.play().catch(()=>{})};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[hero]);useEffect(()=>{document.body.style.overflow=galleryOpen?'hidden':'';const close=(e:KeyboardEvent)=>e.key==='Escape'&&setGalleryOpen(false);window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close)}},[galleryOpen]);if(location.pathname.replace(/\/$/,'')==='/menu')return <MenuPage lang={lang} set={setLang}/>;return <main className={styles.page}>
<header className={styles.header}><a className={styles.brand} href="#home"><img src="/media/brand/logo.jpg"/><span>FUSIÓN<small>RESTAURANTE & BAR</small></span></a><button className={styles.menuButton} onClick={()=>setOpen(!open)}><i/><i/></button><nav className={open?styles.navOpen:''}>{t.nav.map((x,i)=><a key={x} onClick={()=>setOpen(false)} href={['#about','#menu','#sushi','#gallery','#visit'][i]}>{x}</a>)}<a className={styles.reserve} href="#visit">{t.find}</a></nav><Language lang={lang} set={setLang}/></header>
<section className={styles.hero} id="home"><div className={styles.heroMedia} data-parallax>{heroVideos.map((video,i)=><video ref={node=>{heroRefs.current[i]=node}} key={video.desktop} className={hero===i?styles.videoActive:''} muted playsInline loop preload={i===0?'auto':'metadata'} poster={video.poster} aria-hidden={hero!==i}><source media="(max-width: 700px)" src={video.mobile} type="video/mp4"/><source src={video.desktop} type="video/mp4"/></video>)}<i/></div><div className={`${styles.heroContent} scroll-reveal`} data-r><p className={styles.eye}>{t.k}</p><h1>{t.h}<br/><em>{t.ha}</em></h1><p>{t.lead}</p><div><a className={styles.primary} href="/menu">{t.explore} ↗</a><a className={styles.textLink} href="#about">{t.story} ↓</a></div></div><div className={styles.videoNav} aria-label="Hero videos">{heroVideos.map((_,i)=><button className={hero===i?styles.active:''} onClick={()=>setHero(i)} key={i} aria-label={`Video ${i+1}`} aria-current={hero===i?'true':undefined}>0{i+1}</button>)}</div></section>
<div className={styles.ticker}><div>{[...t.tick,...t.tick].map((x,i)=><span key={i}>{x} <b>✦</b></span>)}</div></div>
<section className={styles.about} id="about"><div className={styles.copy} data-r><p className={styles.eye}>{t.ak}</p><h2>{t.ah}</h2><p>{t.ap}</p><blockquote>“{t.quote}”<small>Steven Varela Jiménez · Executive Chef</small></blockquote></div><div className={styles.chef} data-r><img src="/media/chef/chef2.jpg"/><img src="/media/chef/chef6.jpg"/><span>CHEF<br/>STEVEN</span></div></section>
<section className={styles.menuSection} id="menu"><div className={styles.menuVisual} data-r><img src="/media/menu/menu3.jpg"/><img src="/media/menu/menu6.jpg"/><span>08<small>PAGES</small></span></div><div className={styles.copy} data-r><p className={styles.eye}>{t.mk}</p><h2>{t.mh}</h2><p>{t.mp}</p><div className={styles.actions}><a className={styles.primary} href="/menu">{t.open} ↗</a><a className={styles.secondary} href="/downloads/fusion-sushi-menu.pdf" download>{t.down} ↓</a></div></div></section>
<section className={`${styles.sushi} sushi-japan`} id="sushi"><i className={styles.sun}/><span className="kanji kanji-left">寿司</span><span className="kanji kanji-right">日本</span><div className={styles.sushiHead} data-r><p>{t.sk}</p><h2>{t.sh1}<b>♥</b>{t.sh2}</h2><p>{t.sp}</p></div><div className={styles.sushiRail}>{sushi.map((src,i)=><figure data-r key={src}><img data-parallax src={src}/><figcaption><span>鮨</span>0{i+1}</figcaption></figure>)}</div></section>
<section className={styles.gallery} id="gallery"><header data-r><div><p className={styles.eye}>{t.gk}</p><h2>{t.gh}</h2></div><p>{t.gp}</p></header><div className={styles.foodGrid}>{food.slice(0,5).map((src,i)=><figure className={i===0?styles.wide:''} data-r key={src}><img data-parallax src={src}/><span>0{i+1}</span></figure>)}</div><div className="gallery-more" data-r><button className={styles.primary} onClick={()=>setGalleryOpen(true)}>{galleryDetails[lang].more} <span>↗</span></button></div></section>
{galleryOpen&&<div className="gallery-modal" role="dialog" aria-modal="true" aria-label={galleryDetails[lang].title}><header><div><small>FUSIÓN · COCINA CREATIVA</small><h2>{galleryDetails[lang].title}</h2></div><button onClick={()=>setGalleryOpen(false)} aria-label={galleryDetails[lang].close}>×<span>{galleryDetails[lang].close}</span></button></header><div className="gallery-modal-grid">{food.map((src,i)=><figure key={src}><img src={src} alt={`Fusion dish ${i+1}`}/><figcaption>FUSIÓN <span>{String(i+1).padStart(2,'0')}</span></figcaption></figure>)}</div></div>}
<section className={styles.visit} id="visit"><div className={styles.visitImages}><img src="/media/restaurant/fusion01.jpg"/><img src="/media/restaurant/fusion02.jpg"/></div><div className={styles.visitCard} data-r><p className={styles.eye}>{t.vk}</p><h2>{t.vh}</h2><p>{visitDetails[lang].text}</p><div className={styles.map}><iframe title="Restaurante y Bar Fusión on Google Maps" loading="lazy" src="https://www.google.com/maps?q=9.0808814,-83.6634834&z=16&output=embed"/><span>9.0808814° N · 83.6634834° W</span></div><a className={styles.primary} target="_blank" rel="noreferrer" href={mapUrl}>{visitDetails[lang].button} ↗</a><a className={styles.secondary} href="mailto:info@fusion-sushi.com">{t.contact}</a></div></section>
<footer className={`${styles.footer} premium-footer`}><div className="footer-brand"><img src="/media/brand/logo.jpg"/><div><strong>FUSIÓN SUSHI</strong><p>{t.foot}</p></div></div><div className="footer-nav"><small>EXPLORE</small><a href="#about">{t.nav[0]}</a><a href="/menu">{t.nav[1]}</a><a href="#gallery">{t.nav[3]}</a></div><div className="footer-visit"><small>VISIT US</small><p>{galleryDetails[lang].location}<br/>9.0808814, -83.6634834</p><a target="_blank" rel="noreferrer" href={mapUrl}>{galleryDetails[lang].directions} ↗</a></div><div className="footer-bottom"><p>© {new Date().getFullYear()} Restaurante y Bar Fusión</p><p>{t.by} <a target="_blank" href="https://puravidawebs.com">puravidawebs.com ↗</a></p></div></footer></main>}
export default App
