import { useEffect, useState } from 'react'
import styles from './App.module.css'
type Lang='en'|'es'|'fr'
const C={
en:{nav:['Story','Menu','We ♥ Sushi','Gallery','Visit'],find:'Find us',k:'Creative cuisine · Costa Rica',h:'Where the world meets',ha:'the fire.',lead:'A borderless dining experience by Chef Steven Varela Jiménez—bold sushi, tropical ingredients and plates made with soul.',explore:'Explore the menu',story:'Our story',tick:['International cuisine','We love sushi','Special events','Catering service','Craft beer'],ak:'The chef behind the vision',ah:'Technique, instinct, and a world of flavor.',ap:'Chef Steven Varela Jiménez transforms Costa Rica’s abundance into expressive cuisine. His kitchen moves freely between Japanese precision, Latin warmth and international technique—always guided by fresh ingredients and generous hospitality.',quote:'Every plate should feel familiar for one second—and completely new the next.',mk:'Eight pages of possibilities',mh:'A menu without borders.',mp:'Sushi, seafood, premium cuts, vibrant salads and comforting classics—created for every kind of craving.',open:'Open full menu',down:'Download PDF',sk:'鮨 · Japanese craft, tropical soul',sh1:'We ',sh2:' Sushi',sp:'Hand-rolled. Fearlessly creative. Made to order with selected seafood, balanced rice and unexpected Costa Rican character.',gk:'From our kitchen',gh:'Food worth gathering around.',gp:'A visual taste of the dishes, colors and details that define Fusión.',vk:'Come as you are',vh:'Your table is waiting.',vp:'Share the exact Google Maps link, phone number and opening hours with us and this panel is ready to go live.',maps:'Open Google Maps',contact:'Contact restaurant',foot:'Creative cuisine · Sushi · Good times',by:'Website created by',full:'Full Menu',back:'Back to restaurant',mi:'Browse every page or download the complete menu for offline access.'},
es:{nav:['Historia','Menú','Amamos el sushi','Galería','Visítanos'],find:'Cómo llegar',k:'Cocina creativa · Costa Rica',h:'Donde el mundo se encuentra con',ha:'el fuego.',lead:'Una experiencia sin fronteras del chef Steven Varela Jiménez: sushi audaz, ingredientes tropicales y platos hechos con alma.',explore:'Explorar el menú',story:'Nuestra historia',tick:['Comida internacional','Amamos el sushi','Eventos especiales','Servicio de catering','Cerveza artesanal'],ak:'El chef detrás de la visión',ah:'Técnica, instinto y un mundo de sabor.',ap:'El chef Steven Varela Jiménez transforma la abundancia de Costa Rica en una cocina expresiva. Su propuesta une precisión japonesa, calidez latina y técnica internacional, siempre con ingredientes frescos y hospitalidad genuina.',quote:'Cada plato debe sentirse familiar por un segundo y completamente nuevo al siguiente.',mk:'Ocho páginas de posibilidades',mh:'Un menú sin fronteras.',mp:'Sushi, mariscos, cortes premium, ensaladas vibrantes y clásicos reconfortantes para todos los gustos.',open:'Abrir menú completo',down:'Descargar PDF',sk:'鮨 · Arte japonés, alma tropical',sh1:'Amamos el ',sh2:' Sushi',sp:'Enrollado a mano, creativo y preparado al momento con mariscos seleccionados, arroz equilibrado y carácter costarricense.',gk:'Desde nuestra cocina',gh:'Comida para compartir.',gp:'Una mirada a los platos, colores y detalles que definen a Fusión.',vk:'Ven como eres',vh:'Tu mesa te espera.',vp:'Compártenos el enlace exacto de Google Maps, teléfono y horario para dejar este panel listo para publicar.',maps:'Abrir Google Maps',contact:'Contactar restaurante',foot:'Cocina creativa · Sushi · Buenos momentos',by:'Página creada por',full:'Menú completo',back:'Volver al restaurante',mi:'Explora cada página o descarga el menú completo.'},
fr:{nav:['Histoire','Menu','Nous ♥ Sushi','Galerie','Visite'],find:'Nous trouver',k:'Cuisine créative · Costa Rica',h:'Là où le monde rencontre',ha:'le feu.',lead:'Une expérience sans frontières du chef Steven Varela Jiménez : sushi audacieux, ingrédients tropicaux et assiettes pleines d’âme.',explore:'Explorer le menu',story:'Notre histoire',tick:['Cuisine internationale','Nous aimons le sushi','Événements spéciaux','Service traiteur','Bière artisanale'],ak:'Le chef derrière la vision',ah:'Technique, instinct et un monde de saveurs.',ap:'Le chef Steven Varela Jiménez transforme l’abondance du Costa Rica en cuisine expressive, entre précision japonaise, chaleur latine et technique internationale.',quote:'Chaque assiette doit sembler familière une seconde, puis entièrement nouvelle.',mk:'Huit pages de possibilités',mh:'Un menu sans frontières.',mp:'Sushi, fruits de mer, viandes premium, salades vibrantes et grands classiques.',open:'Ouvrir le menu',down:'Télécharger le PDF',sk:'鮨 · Art japonais, âme tropicale',sh1:'Nous ',sh2:' Sushi',sp:'Roulé à la main, créatif et préparé sur commande avec des produits sélectionnés et un caractère costaricien.',gk:'Depuis notre cuisine',gh:'Une cuisine à partager.',gp:'Les plats, couleurs et détails qui définissent Fusión.',vk:'Venez comme vous êtes',vh:'Votre table vous attend.',vp:'Partagez le lien Google Maps exact, le téléphone et les horaires pour finaliser ce panneau.',maps:'Ouvrir Google Maps',contact:'Contacter le restaurant',foot:'Cuisine créative · Sushi · Bons moments',by:'Site créé par',full:'Menu complet',back:'Retour au restaurant',mi:'Parcourez chaque page ou téléchargez le menu complet.'}}
const sushi=[1,2,3,4,5,6,7,8,9,10].map(n=>`/media/sushi/sushi${String(n).padStart(2,'0')}.jpg`)
const food=[1,8,11,3,13,9,7,10,6,4,5].map(n=>`/media/food/comida${n}.jpg`)
const menus=[1,2,3,4,5,6,7,8].map(n=>`/media/menu/menu${n}.jpg`)
const mapUrl='https://www.google.com/maps/place/Restaurante+y+Bar+Fusi%C3%B3n/@9.0806844,-83.6667255,15.25z/data=!4m9!1m2!2m1!1sfusion!3m5!1s0x8fa3fe8e55a99541:0xc77a745b73b5d020!8m2!3d9.0808814!4d-83.6634834!16s%2Fg%2F11c2pq9rt8?entry=ttu'
const visitDetails={
  en:{text:'Plan your visit to Restaurante y Bar Fusión. Explore the interactive map or open Google Maps for turn-by-turn directions.',button:'Get directions'},
  es:{text:'Planea tu visita a Restaurante y Bar Fusión. Explora el mapa interactivo o abre Google Maps para recibir indicaciones paso a paso.',button:'Cómo llegar'},
  fr:{text:'Planifiez votre visite au Restaurante y Bar Fusión. Consultez la carte interactive ou ouvrez Google Maps pour obtenir votre itinéraire.',button:'Obtenir l’itinéraire'},
}
const galleryDetails={
  en:{more:'View more dishes',title:'The Fusión Gallery',close:'Close gallery',location:'Restaurante y Bar Fusión · Costa Rica',directions:'Directions'},
  es:{more:'Ver más platillos',title:'Galería Fusión',close:'Cerrar galería',location:'Restaurante y Bar Fusión · Costa Rica',directions:'Cómo llegar'},
  fr:{more:'Voir plus de plats',title:'Galerie Fusión',close:'Fermer la galerie',location:'Restaurante y Bar Fusión · Costa Rica',directions:'Itinéraire'},
}
function Language({lang,set}:{lang:Lang,set:(v:Lang)=>void}){return <div className={styles.lang}>{(['en','es','fr'] as Lang[]).map(x=><button className={lang===x?styles.active:''} onClick={()=>set(x)} key={x}>{x.toUpperCase()}</button>)}</div>}
function MenuPage({lang,set}:{lang:Lang,set:(v:Lang)=>void}){const t=C[lang];return <main className={styles.menuPage}><header className={styles.menuTop}><a href="/">← {t.back}</a><Language lang={lang} set={set}/></header><section className={styles.menuIntro}><span>FUSIÓN · SUSHI</span><h1>{t.full}</h1><p>{t.mi}</p><a className={styles.primary} href="/downloads/fusion-sushi-menu.pdf" download>{t.down} ↓</a></section><div className={styles.menuPages}>{menus.map((src,i)=><figure key={src}><span>{i+1} / 08</span><img src={src} alt={`Menu page ${i+1}`}/></figure>)}</div></main>}
function App(){const[lang,setLang]=useState<Lang>('en'),[open,setOpen]=useState(false),[hero,setHero]=useState(0),[galleryOpen,setGalleryOpen]=useState(false);const t=C[lang];const vids=['/media/video/cocinallama.mp4','/media/video/sushi1.mp4','/media/video/sushi2.mp4'];useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle(styles.visible,e.isIntersecting)),{threshold:.08,rootMargin:'-5% 0px -8%'});document.querySelectorAll('[data-r]').forEach(e=>o.observe(e));let ticking=false;const move=()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{document.documentElement.style.setProperty('--page-scroll',`${window.scrollY}px`);document.querySelectorAll<HTMLElement>('[data-parallax]').forEach(el=>{const rect=el.getBoundingClientRect();el.style.setProperty('--parallax',`${(rect.top-window.innerHeight/2)*-.035}px`)});ticking=false})};window.addEventListener('scroll',move,{passive:true});move();return()=>{o.disconnect();window.removeEventListener('scroll',move)}},[]);useEffect(()=>{document.body.style.overflow=galleryOpen?'hidden':'';const close=(e:KeyboardEvent)=>e.key==='Escape'&&setGalleryOpen(false);window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close)}},[galleryOpen]);if(location.pathname.replace(/\/$/,'')==='/menu')return <MenuPage lang={lang} set={setLang}/>;return <main className={styles.page}>
<header className={styles.header}><a className={styles.brand} href="#home"><img src="/media/brand/logo.jpg"/><span>FUSIÓN<small>RESTAURANTE & BAR</small></span></a><button className={styles.menuButton} onClick={()=>setOpen(!open)}><i/><i/></button><nav className={open?styles.navOpen:''}>{t.nav.map((x,i)=><a key={x} onClick={()=>setOpen(false)} href={['#about','#menu','#sushi','#gallery','#visit'][i]}>{x}</a>)}<a className={styles.reserve} href="#visit">{t.find}</a></nav><Language lang={lang} set={setLang}/></header>
<section className={styles.hero} id="home"><div className={styles.heroMedia} data-parallax>{vids.map((v,i)=><video key={v} className={hero===i?styles.videoActive:''} src={v} muted autoPlay playsInline loop/>)}<i/></div><div className={`${styles.heroContent} scroll-reveal`} data-r><p className={styles.eye}>{t.k}</p><h1>{t.h}<br/><em>{t.ha}</em></h1><p>{t.lead}</p><div><a className={styles.primary} href="/menu">{t.explore} ↗</a><a className={styles.textLink} href="#about">{t.story} ↓</a></div></div><div className={styles.videoNav}>{vids.map((_,i)=><button className={hero===i?styles.active:''} onClick={()=>setHero(i)} key={i}>0{i+1}</button>)}</div></section>
<div className={styles.ticker}><div>{[...t.tick,...t.tick].map((x,i)=><span key={i}>{x} <b>✦</b></span>)}</div></div>
<section className={styles.about} id="about"><div className={styles.copy} data-r><p className={styles.eye}>{t.ak}</p><h2>{t.ah}</h2><p>{t.ap}</p><blockquote>“{t.quote}”<small>Steven Varela Jiménez · Executive Chef</small></blockquote></div><div className={styles.chef} data-r><img src="/media/chef/chef2.jpg"/><img src="/media/chef/chef6.jpg"/><span>CHEF<br/>STEVEN</span></div></section>
<section className={styles.menuSection} id="menu"><div className={styles.menuVisual} data-r><img src="/media/menu/menu3.jpg"/><img src="/media/menu/menu6.jpg"/><span>08<small>PAGES</small></span></div><div className={styles.copy} data-r><p className={styles.eye}>{t.mk}</p><h2>{t.mh}</h2><p>{t.mp}</p><div className={styles.actions}><a className={styles.primary} href="/menu">{t.open} ↗</a><a className={styles.secondary} href="/downloads/fusion-sushi-menu.pdf" download>{t.down} ↓</a></div></div></section>
<section className={`${styles.sushi} sushi-japan`} id="sushi"><i className={styles.sun}/><span className="kanji kanji-left">寿司</span><span className="kanji kanji-right">日本</span><div className={styles.sushiHead} data-r><p>{t.sk}</p><h2>{t.sh1}<b>♥</b>{t.sh2}</h2><p>{t.sp}</p></div><div className={styles.sushiRail}>{sushi.map((src,i)=><figure data-r key={src}><img data-parallax src={src}/><figcaption><span>鮨</span>0{i+1}</figcaption></figure>)}</div></section>
<section className={styles.gallery} id="gallery"><header data-r><div><p className={styles.eye}>{t.gk}</p><h2>{t.gh}</h2></div><p>{t.gp}</p></header><div className={styles.foodGrid}>{food.slice(0,5).map((src,i)=><figure className={i===0?styles.wide:''} data-r key={src}><img data-parallax src={src}/><span>0{i+1}</span></figure>)}</div><div className="gallery-more" data-r><button className={styles.primary} onClick={()=>setGalleryOpen(true)}>{galleryDetails[lang].more} <span>↗</span></button></div></section>
{galleryOpen&&<div className="gallery-modal" role="dialog" aria-modal="true" aria-label={galleryDetails[lang].title}><header><div><small>FUSIÓN · COCINA CREATIVA</small><h2>{galleryDetails[lang].title}</h2></div><button onClick={()=>setGalleryOpen(false)} aria-label={galleryDetails[lang].close}>×<span>{galleryDetails[lang].close}</span></button></header><div className="gallery-modal-grid">{food.map((src,i)=><figure key={src}><img src={src} alt={`Fusion dish ${i+1}`}/><figcaption>FUSIÓN <span>{String(i+1).padStart(2,'0')}</span></figcaption></figure>)}</div></div>}
<section className={styles.visit} id="visit"><div className={styles.visitImages}><img src="/media/restaurant/fusion01.jpg"/><img src="/media/restaurant/fusion02.jpg"/></div><div className={styles.visitCard} data-r><p className={styles.eye}>{t.vk}</p><h2>{t.vh}</h2><p>{visitDetails[lang].text}</p><div className={styles.map}><iframe title="Restaurante y Bar Fusión on Google Maps" loading="lazy" src="https://www.google.com/maps?q=9.0808814,-83.6634834&z=16&output=embed"/><span>9.0808814° N · 83.6634834° W</span></div><a className={styles.primary} target="_blank" rel="noreferrer" href={mapUrl}>{visitDetails[lang].button} ↗</a><a className={styles.secondary} href="mailto:info@fusion-sushi.com">{t.contact}</a></div></section>
<footer className={`${styles.footer} premium-footer`}><div className="footer-brand"><img src="/media/brand/logo.jpg"/><div><strong>FUSIÓN SUSHI</strong><p>{t.foot}</p></div></div><div className="footer-nav"><small>EXPLORE</small><a href="#about">{t.nav[0]}</a><a href="/menu">{t.nav[1]}</a><a href="#gallery">{t.nav[3]}</a></div><div className="footer-visit"><small>VISIT US</small><p>{galleryDetails[lang].location}<br/>9.0808814, -83.6634834</p><a target="_blank" rel="noreferrer" href={mapUrl}>{galleryDetails[lang].directions} ↗</a></div><div className="footer-bottom"><p>© {new Date().getFullYear()} Restaurante y Bar Fusión</p><p>{t.by} <a target="_blank" href="https://puravidawebs.com">puravidawebs.com ↗</a></p></div></footer></main>}
export default App
